MONGODB_CONFIG:
  name: "lowercode_mongo"              # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://root:root@localhost:27017/lowercode?authSource=admin"   # 数据库链接地址   # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: false                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能
MYSQL_CONFIG:
  name: "lowercode_mysql"
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "root"
  database: "lowercode_material"
  entities: "mysql"
  logging: true
  synchronize: true
